{
 "title": "Escooters demand monitoring",
 "time": { "from": "2020-10-08T00:00:00.000Z", "to": "2020-10-16T00:00:00.000Z" },
 "panels": [
  {
   "title": "Number of drifted features",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM escooter_demand_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share missing values",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM escooter_demand_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM escooter_demand_metrics LIMIT 50 "
    }
   ]
  }
 ]
}