FROM python:3.10.9

WORKDIR /app

RUN pip3 install --upgrade pip
ENV PYTHONPATH=${PYTHONPATH}:${PWD}
RUN pip3 install poetry
RUN poetry config virtualenvs.create false
COPY [ "poetry.lock", "pyproject.toml", "./" ]
RUN poetry install --without dev,train

COPY [ "src/api/predict.py", "models/model.txt", "./" ]
COPY [ "references/community_codes_dict.pkl", "./community_codes_dict.pkl" ]
COPY [ "data/external/boundaries.json", "./boundaries.json" ]
COPY [ "data/external/city_center_coordinates.txt", "./city_center_coordinates.txt" ]

EXPOSE 9696

ENTRYPOINT [ "gunicorn", "--bind=0.0.0.0:9696", "predict:app" ]
